name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postares:
        image: postgres:latest
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmdpq_isready
          --health-interval10s
          -_health-timeout 5s
          --health-retries5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
